#!/bin/bash

# Instruções para deploy no GitHub Pages
echo "===== Instruções para Deploy no GitHub Pages ====="
echo ""
echo "1. Clone o repositório para sua máquina local:"
echo "   git clone https://github.com/gabrielalves939/gabrielalves939portifolio.git"
echo "   cd gabrielalves939portifolio"
echo ""
echo "2. Atualize seu repositório local com as alterações recentes:"
echo "   git pull origin main"
echo ""
echo "3. Envie as alterações para o GitHub:"
echo "   git push origin main"
echo ""
echo "4. Configurar o GitHub Pages:"
echo "   a. Acesse https://github.com/gabrielalves939/gabrielalves939portifolio/settings/pages"
echo "   b. Em 'Source', selecione o branch 'main'"
echo "   c. Selecione a pasta '/ (root)' para que o index.html seja usado"
echo "   d. Clique em 'Save'"
echo ""
echo "Seu site estará disponível em:"
echo "https://gabrielalves939.github.io/gabrielalves939portifolio/"
echo ""
echo "==========================================="
echo "OBSERVAÇÃO: Se você estiver em sua máquina local, pode executar os seguintes comandos:"
echo "git push origin main"
echo "==========================================="